###
POST http://localhost:3100/api/v1/user/signin HTTP/1.1
Content-Type: application/json

{
    "firstname":"test",
    "lastname":"test",
    "email":"test123443@test.com",
    "password":"user1223",
    "repeatPassword":"user1223"
}

###
POST http://localhost:3100/api/v1/user/login HTTP/1.1
Content-Type: application/json

{
    "email":"juli1234@gmail.com",
    "password":"hola1233"
}

###
GET http://localhost:3100/api/v1/user/get-me/6540a02cdd50642f673811bf HTTP/1.1